##authors meteor##
##使用问题联系qq 2260483272
setting:
  #玩家默认能创建几块广告
  normal: 1
  #创建广告所花费的游戏币
  money: 1000
#屏蔽词
black:
  - '正业'
  - '妈妈'
  - 'meteor'
#建筑类型显示名称
type:
  shop: '&a商店'
  mobspanwner: '&c刷怪场'
  town: '&6小镇'
  other: '&b其他'
#
item:
  name: '%ad_name%'
  ID: 'PAPER'
  data: 0
  lore:
    - '&8&l&m &7&l&m              &8&l&m '
    - '&a建筑类型 - %type%'
    - '&a所在世界 - %world%'
    - '&a建筑主人 - %owner%'
    - '&a创建时间 - &6%time%'
    - '&d爱心数: - %like%'
    - '&6左键传送 / &6右键点爱心'
    - '&8&l&m &7&l&m              &8&l&m '
    - '&f[ &6介绍 &f]'
  sub-lore:
    - '&8&l&m &7&l&m              &8&l&m '